"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowRight, Ticket, CheckCircle2 } from "lucide-react";

export default function SignupPage() {
  const [token, setToken] = useState("");
  const [isValidating, setIsValidating] = useState(false);

  const handleContinue = (e: React.FormEvent) => {
    e.preventDefault();
    if (!token.trim()) return;
    setIsValidating(true);
    // Add artificial small delay to make the UX elegant and not jarring
    setTimeout(() => {
      window.location.href = `/auth/invite/${encodeURIComponent(token.trim())}`;
    }, 400);
  };

  return (
    <div className="min-h-screen w-full flex bg-white dark:bg-black relative overflow-hidden">
      
      {/* Background ambient lighting */}
      <div className="absolute inset-0 z-0">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-red-600/5 rounded-full blur-[120px]"></div>
      </div>

      <div className="relative z-10 w-full flex flex-col items-center justify-center p-4">
        
        {/* Main Card */}
        <div className="w-full max-w-md bg-white/70 dark:bg-gray-900/50 backdrop-blur-xl border border-gray-200 dark:border-gray-800 rounded-3xl p-10 shadow-2xl">
          
          <div className="flex flex-col items-center text-center space-y-4 mb-8">
            <div className="w-16 h-16 bg-gradient-to-br from-red-600 to-red-500 rounded-2xl flex items-center justify-center shadow-[0_8px_24px_rgba(220,38,38,0.4)] mb-2">
              <Ticket className="w-8 h-8 text-white" />
            </div>
            <h1 className="text-3xl font-black tracking-tight text-black dark:text-white">Join the platform</h1>
            <p className="text-muted-foreground text-sm max-w-xs">
              If you received an exclusive invitation securely paste your token below to register.
            </p>
          </div>

          <form onSubmit={handleContinue} className="space-y-6">
            <div className="space-y-2">
              <Label htmlFor="token" className="text-xs uppercase font-bold tracking-wider text-gray-500">Invitation Token</Label>
              <div className="relative group">
                <Input
                  id="token"
                  value={token}
                  onChange={(e) => setToken(e.target.value)}
                  placeholder="Paste secure token"
                  className="h-14 bg-gray-50 dark:bg-black/50 border-gray-200 dark:border-gray-800 focus-visible:ring-red-600 focus-visible:border-red-600 font-mono text-center tracking-widest text-lg shadow-inner"
                />
              </div>
            </div>

            <Button 
              type="submit" 
              disabled={!token.trim() || isValidating}
              className="w-full h-14 bg-black hover:bg-gray-900 dark:bg-white dark:hover:bg-gray-200 text-white dark:text-black font-bold text-base shadow-lg transition-transform active:scale-95 flex items-center justify-center gap-2"
            >
              {isValidating ? (
                <>
                  <CheckCircle2 className="w-5 h-5 animate-pulse text-green-500" />
                  Verifying Token...
                </>
              ) : (
                <>
                  Continue Registration <ArrowRight className="w-5 h-5" />
                </>
              )}
            </Button>
          </form>

          <div className="mt-8 text-center text-xs text-gray-400 font-medium">
            Invitations are strictly generated by Organization Administrators.
          </div>
        </div>

      </div>
    </div>
  );
}
