/* Convert ref static-ref-article.html into app/[slug]/article-html.ts
   (a single TS template string with sentinels filled at runtime). */
const fs = require("fs");
const path = require("path");

const REF_DIR = "C:/Users/jam/Desktop/Dailytips/ref-static-full-website/wp.quomodosoft.com/newsprk";
const OUT = path.join(__dirname, "..", "app", "[slug]", "article-html.ts");

const html = fs.readFileSync(path.join(REF_DIR, "static-ref-article.html"), "utf8");

const bodyStart = html.indexOf("<body");
const bodyOpenEnd = html.indexOf(">", bodyStart);
const bodyEnd = html.lastIndexOf("</body>");
let s = html.slice(bodyOpenEnd + 1, bodyEnd);

s = s.replace(/<script[\s\S]*?<\/script>/gi, "");

s = s.replace(/\/wp-content\/uploads\//g, "/uploads/");

const missing = [];

function rep(label, re, to) {
  const before = s;
  s = s.replace(re, to);
  if (s === before) missing.push(label);
  return s;
}

rep("TITLE", /(<h1>)[\s\S]*?(<\/h1>)/, "$1__ARTICLE_TITLE__$2");
rep(
  "EXCERPT",
  /(<div class="single_post_heading">[\s\S]*?<p>)[\s\S]*?(<\/p>)/,
  "$1__ARTICLE_EXCERPT__$2"
);
rep("CAT_URL", /(class="post-cat"\s+href=")[^"]*(")/, "$1__ARTICLE_CAT_URL__$2");
rep(
  "CAT_LABEL",
  /(class="post-cat"\s+href="__ARTICLE_CAT_URL__")[\s\S]*?(<\/a>)/,
  "$1__ARTICLE_CAT_LABEL__$2"
);
rep(
  "META_DATE",
  /(<i class="fal fa-clock"><\/i>)[\s\S]*?(<\/li>)/,
  "$1 __ARTICLE_META_DATE__</li>"
);
rep(
  "META_VIEWS",
  /(<i class="fal fa-eye"><\/i>)[\s\S]*?(<\/li>)/,
  "$1 __ARTICLE_META_VIEWS__</li>"
);
rep(
  "HERO_SRC",
  /(<div class="video_img">[\s\S]*?<img[^>]*?src=")[^"]*(")/,
  "$1__ARTICLE_HERO_SRC__$2"
);
rep(
  "HERO_ALT",
  /(<div class="video_img">[\s\S]*?alt=")[^"]*(")/,
  "$1__ARTICLE_HERO_ALT__$2"
);
rep(
  "AUTHOR_NAME",
  /(<div class="author__data">[\s\S]*?<a href="[^"]*">)[\s\S]*?(<\/a>)/,
  "$1__ARTICLE_AUTHOR_NAME__$2"
);
rep(
  "AUTHOR_DATE",
  /(<div class="author__data">[\s\S]*?<\/a>[\s\S]*?<span>)[\s\S]*?(<\/span>)/,
  "$1__ARTICLE_AUTHOR_DATE__$2"
);

const contentStart = s.indexOf('<div class="content">');
const articleEnd = s.indexOf("</article>");
if (contentStart === -1 || articleEnd === -1) {
  throw new Error("content or article container not found");
}
const contentClose = s.lastIndexOf("</div>", articleEnd);
if (contentClose < contentStart) throw new Error("content close not found");
s = s.slice(0, contentStart + '<div class="content">'.length) + "__ARTICLE_CONTENT__" + s.slice(contentClose);

if (missing.length) {
  console.error("FAILED replacements:", missing);
  process.exit(1);
}

const out = `// GENERATED by scripts/convert-article.cjs from ref static-ref-article.html.\n// Do not edit by hand. Sentinels (__ARTICLE_*) are replaced at runtime in app/[slug]/page.tsx.\nexport const ARTICLE_HTML = \`\n${s}\n\`;\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out, "utf8");
console.log("OK wrote", OUT, (out.length / 1024).toFixed(1), "KB, sentinels:", (s.match(/__ARTICLE_[A-Z_]+__/g) || []).length);